version: '3'
services:
  web:
    build: .
    ports:
      - 3000:8080
      - 3001:8081
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ny_cab_data
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
